buildingSMART/BCF-API

README.md

Here's the small change we discussed in the telco
References:
https://tools.ietf.org/html/rfc6749#section-2.3.1 The OAuth 2.0 Authorization Framework / 2.3.1 Client Password
https://tools.ietf.org/html/rfc6749#section-4.1.3 The OAuth 2.0 Authorization Framework / 4.1.3 Access Token Request

Token Request specification to allow all parameters in the request body

---

README.md
Schemas_draft-03/Authentication/auth_GET.json

Change to include optional support for optional Http Basic Authentication from BCF API servers as discussed in the Munich Hackathon.

Support for Http Basic Authentication

---

Schemas_draft-03/Collaboration/Comment/comment_GET.json

It's currently required by the schema when retrieving comments, which it shouldnt be=)

Fix to Make Comments "modified_date" Property Optional

---

README.md

Suggestion to use the regular ISO 8601 format for DateTime representation. The same is used in Xml and is becoming very common in Json APIs as discussed in the Munich Hackathon.

Explicit Specificiation of the Serialization Format for DateTime in Json

---

Schemas_draft-03/Collaboration/File/file_GET.json
Schemas_draft-03/Collaboration/File/file_PATCH.json
Schemas_draft-03/Collaboration/File/file_PUT.json

Currently the date of referenced Ifc files is required, this is making the actual file date optional since it's not a real identifier and therefore shouldn't be enforced.

Change IfcFiles "file_date" Property to be Optional

---

README.md

Just replaced section 1.5 with links to Wikipedia (for a brief summary) and the actual Http/1.1 specification. There's no need to specify anything ourselves. This was discussed in the Implementers Group on 23.11.2015.

Removed Custom Definition of Http Status Codes

---

README.md
Schemas_draft-03/Collaboration/Topic/topic_GET.json
Schemas_draft-03/Collaboration/Topic/topic_PATCH.json
Schemas_draft-03/Collaboration/Topic/topic_POST.json
Schemas_draft-03/Collaboration/Topic/topic_PUT.json

This just adds the capability of having multiple `reference_link`s within a topic.
I also changed the properties table for the topic object to be a Markdown table instead of Html for better readability and compatibility with Markdown editors. (This will create merge errors with the other pull requests=)

Changed topic Objects "reference_links" Property to be an Array

---

README.md
Schemas_draft-03/Collaboration/Comment/comment_GET.json
Schemas_draft-03/Collaboration/Comment/comment_PATCH.json
Schemas_draft-03/Collaboration/Comment/comment_POST.json
Schemas_draft-03/Collaboration/Comment/comment_PUT.json

[Fix for Issue 19](https://github.com/BuildingSMART/BCF-API/issues/19) due to the status and verbal_status being deprecated in BCF XML.
Only the topic object itself should be responsibly for handling it's status and the creation or modification of a comment does not result in an implicit change of topic status.
I also changed the properties table for the comment object to be a Markdown table instead of Html for better readability and compatibility with Markdown editors.

Removed comment Objects "status" and "verbal_status" Properties

---

README.md

Would love some feedback here=)
This just puts a static link to the API specification at v1.0 at the top of the readme

Add link to fixed v1.0 spec and clarify other link to lead to the BCF XML repo

---

README.md
Schemas_draft-03/Collaboration/Comment/comment_POST.json
Schemas_draft-03/Collaboration/DocumentReference/document_reference_POST.json
Schemas_draft-03/Collaboration/Topic/topic_POST.json
Schemas_draft-03/Collaboration/Viewpoint/viewpoint_POST.json

Fix broken roundtrip by allowing guid's in create requests

Fix broken roundtrip by allowing guid's in create requests

---

README.md

Topic priority has been added as Odata filter parameter for BCF API 2.2
Fixes #208 
Testing
-------
1. Tested by verifying that priority OData filter parameter is shown properly in the correct section

Issue #208: Add priority filtering option for BCF API 2.2

---

README.md

#214  remove redundant '#' from colors in viewpoint examples.

Issue #214: remove redundant '#' from colors in viewpoint examples.

---

README.md

Added ability to sort by `server_id`, matching its sort/search capability to what is currently supported for `index`.

Ability to sort by server_id

---

README.md

See https://github.com/buildingSMART/BCF-XML/issues/197

DateTime values default to UTC when no timezone is specified

---

README.md

Add note stating that index property is deprecated

---

README.md

Information added regarding the Topic modification date update upon latest topic and comment modification and floating viewpoint addition.
Testing Details:

Issue #211 : Clarify the workflow for Topic Modification date upon Comment modification and floating viewpoint addition

---

README.md

Made it consistent with latest BCF-XML specification.

Clarify ifc_guid as optional in docs

---

README.md

#245 Added 409 Conflict status code when desired GUID conflicts with those existing in target system.

#245 Added 409 Conflict status code when desired GUID conflicts

---

README.md

The BCF API on SwaggerHub was renamed, this PR updates the link to it.

Update link to BCF API on SwaggerHub

---

README.md

Following https://github.com/buildingSMART/BCF-XML/issues/353 
and 
https://github.com/buildingSMART/BCF-XML/pull/357

Clarify units of numeric values

---

README.md
Schemas_draft-03/Collaboration/RelatedTopic/related_topic_GET.json
Schemas_draft-03/Collaboration/RelatedTopic/related_topic_PUT.json
Schemas_draft-03/Collaboration/Topic/topic_GET.json
Schemas_draft-03/Project/extensions_GET.json

All existing relations defaults to relationType: "relates" 
When adding a child relation to a topic, and getting relations for the child, the "parent" relation should be returned
When adding a parent relation to a topic, and getting relations for the parent, the "child" relation should be returned
Parent/child relations that ends up in an infinite loop should be blocked
Include of topic relations PR is here: #315

Add parent/child relation

---

README.md

I've based this on the latest `release_3_0` branch, and it also includes two commits that weren't part of `master` yet.

Fix typo, and merge `release_3_0` into `master`

---

swagger.yaml

The readOnly flag will determin if certain values can be updated by the end user.
If is done the same way as the "readOnly" flag we have made on custom fields already
#352

Add readOnly
