README.md, Schemas_draft-03/Collaboration/Topic/topic_GET.json, Schemas_draft-03/Collaboration/Topic/topic_PATCH.json, Schemas_draft-03/Collaboration/Topic/topic_POST.json, Schemas_draft-03/Collaboration/Topic/topic_PUT.json
I also changed the properties table for the topic object to be a Markdown table instead of Html for better readability and compatibility with Markdown editors.
=> Addition of "due_date" Property in the topic Object

README.md, Schemas_draft-03/Public/version_GET.json
I also changed the properties table for the auth object to be a Markdown table instead of Html for better readability and compatibility with Markdown editors.
=> Changed version Resource to Return a List of Supported Versions

README.md
=> Update section 1.4 to be implementation agnostic

README.md, Schemas_draft-03/Collaboration/Viewpoint/viewpoint_GET.json
Removed the remaining references to viewpoint_actions to reflect that viewpoint is now immutable
=> Remove remaining references to viewpoint_actions (Fix #92)

README.md
As discussed in the last BCF telecon
=> Add explanation about files being possibly stored on the BCF server

README.md, Schemas_draft-03/Collaboration/Action/comment_actions.json, Schemas_draft-03/Collaboration/Action/topic_actions.json
As discussed in todays telecon
d64b9b5 is just an addition of a previously missing url parameter in the examples
=> Delete operations for topic and comment

README.md, Schemas_draft-03/Collaboration/Action/topic_actions.json
=> Make updateDocumentReferences consistent

README.md
=> Add section 1.10 to explain how binary files should be uploaded

README.md
=> Add stage to topic events

README.md, Schemas_draft-03/Collaboration/Action/viewpoint_actions.json, Schemas_draft-03/Collaboration/Viewpoint/viewpoint_GET.json
Add DELETE service for Viewpoints
=> Adding DELETE service for Viewpoints

README.md
Note added for https://github.com/buildingSMART/BCF-API/issues/199
=> Added note that Direction must not be a zero vector.

README.md, Schemas_draft-03/Collaboration/Topic/topic_GET.json
=> Added server_id to support server controlled, user friendly identifiers 

README.md
#213 suggest a change to the documentation to clarify authorization for topic status
=> #213 clarify topic field authorization

README.md, Schemas_draft-03/Project/extensions_GET.json
=> Rename user id type

README.md, Schemas_draft-03/Collaboration/Comment/comment_GET.json, Schemas_draft-03/Collaboration/Comment/comment_POST.json, Schemas_draft-03/Collaboration/Comment/comment_PUT.json
Also clarified either a comment text or a viewpoint must be provided.
And fixed a few broken section references.
=> Remove reply_to_comment_guid from comment schema.

README.md
=> #247: Add note about snapshot max dimension to README

README.md
=> Identifying guids

README.md, Schemas/Collaboration/Viewpoint/components.json, Schemas/Collaboration/Viewpoint/translucency.json, Schemas/Collaboration/Viewpoint/translucency_GET.json, Schemas/Collaboration/Viewpoint/translucency_setup_hints.json
=> #290 add support for component translucency.

README.md, Schemas/Collaboration/Topic/custom_field.json, Schemas/Project/custom_field.json
=> Allow arrays as custom properties

Schemas/Collaboration/Topic/topic_GET.json, Schemas/Collaboration/Topic/topic_POST.json, Schemas/Collaboration/Topic/topic_PUT.json, swagger.yaml
Also, we were discussing a possible name change from e.g. `main_viewpoint_guid` to `default_viewpoint_guid` to better capture what the property is supposed to represent. Other suggestions are also welcome😀
=> Add main_viewpoint_guid property to Swagger

swagger.yaml
Update to reflect changes from https://github.com/buildingSMART/BCF-API/commit/d92ce0deb550173b204d7c46d83428ee09b098a0
=> Change url parameter names

swagger.yaml
=> Name all list responses

swagger.yaml
=> Auto format swagger file
